from math import comb
# assume stars and bars
# |*|*|*|*|*
# stars are n
# each one must have AT LEAST 1 n
# one s at the start, it's fixed
# |* ? * ? *
# | *? * ?*|
# Think about some stars as pivots
# given k sections, k stars are pivots
# k-1 bars exist
# total number of positions
# k (pivots) + k-1 (bars) + n-k(normal stars)
# (n+k-1) choose (2k-1)
# Assume you have (n+k-1) empty
# positions, and what ever permutation
# is generated by the choose function
# sets the positions of pivot -> bar -> pivot...etc
# Fill in the remaining postion with stars
MOD = 998244353
def build_fact(n, mod= MOD):
    fact = [1] * (n+1)
    for i in range(1, n+1):
        fact[i] = fact[i-1] * i % mod
    invfact = [0] * (n+1)
    invfact[n] = pow(fact[n], mod - 2, mod)

    for i in range(n-1, -1, -1):
        invfact[i] = invfact[i+1] * (i+1) % mod

    return fact, invfact
fact, invfact = build_fact(200)
print(fact[:10], invfact[:10])
def choose (n,k):
	return (fact[n] * invfact[k] * invfact[n-k]) % MOD if 0 <= k <= n else 0

def possible_permutations(n):
    permutations = 0
    for i in range(1, n+1):
        permutations  += choose(n+i-1, 2*i -1)
    return permutations

def solve():
    for _ in range(int(input())):
        n,m = map(int, input().split())
        restrictions = [list(map(int, input().split())) for _ in range(m)]
        total_permutations = possible_permutations(n)
        print(total_permutations)
solve()